jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0' # Match your project framework

      - name: Navigate to Solution Directory
        run: cd Predictive-Healthcare-Management-System

      - name: Restore dependencies
        run: dotnet restore Predictive-Healthcare-Management-System.sln

      - name: Build application
        run: dotnet build Predictive-Healthcare-Management-System.sln --configuration Release

      - name: Publish application
        run: dotnet publish Predictive-Healthcare-Management-System.sln --configuration Release --output ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish
